### ISSUE TITLE
Subtlety

### ISSUE THREAD

**Issue by davecastlevania** [Neglin/ColmarAcademy#2]
https://github.com/Neglin/ColmarAcademy/blob/master/index.html#L3-L9

If I view this on an iPhone device it will not resize but resize on browser resize with desktop. This is an easy fix by adding a meta tag for the viewport. Addthis to `<head>`

`<meta name="viewport" content="width=device-width, initial-scale=1">`

Read more about this issue [here](https://stackoverflow.com/questions/13002731/responsive-design-media-query-not-working-on-iphone)

**Comment by Neglin** [comment]
Thanks for this...I had the same issue on my Samsung Galaxy Note...but i was not sure of the right question to ask.
